### ISSUE TITLE
awsで実行するとエラー

### ISSUE THREAD

**Issue by TakahiroYamamoto** [fumimi2you/Mason#4]

**Comment by fumimi2you** [comment]
なんか、 cv2.findContours 関数、どこかのタイミングで、
戻り値が3個→2個に変更になってるっぽい。

アマゾンとMacそれぞれで、インストールした
pythonの詳しい情報、教えて貰えるかな?

**Comment by TakahiroYamamoto** [comment]
こんな感じでした!

MAC
Python 2.7.10

EC2
Python 2.7.14
Python 3.6.2

**Comment by TakahiroYamamoto** [comment]
openCVのバージョンはこんな感じです。
>>> cv2.__version__

MAC
'3.4.3'

EC2
'4.0.0'

**Comment by fumimi2you** [comment]
よし、opencv のバージョンは、
3.x で使おう！(笑)

**Comment by TakahiroYamamoto** [comment]
入れ替えたら治りやした！
